apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    - image: shibboleth-sp
      context: ./shibboleth-sp/
    - image: httpd
      context: ./httpd/
    - image: tomcat
      context: ./tomcat/

# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
# use the dockerfile profile to build images using Docker instead of Jib
- name: dockerfile
  build:
    artifacts:
      - image: shibboleth-sp
        context: ./shibboleth-sp/
      - image: httpd
        context: ./httpd/
      - image: tomcat
        context: ./tomcat/
